import csv
from copy import copy
from datetime import datetime
from io import BytesIO, StringIO
from typing import Iterable
from zipfile import ZIP_DEFLATED, ZipFile

from openpyxl import Workbook
from reportlab.lib.pagesizes import A4, landscape
from reportlab.lib.units import cm
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer
from xml.sax.saxutils import escape

from app.services.pdf_branding import INK, brand_header, branded_footer, branded_styles, data_table, generated_meta


def display_value(value) -> str:
    return "" if value is None else str(value)


def rows_to_csv(headers: list[str], rows: Iterable[Iterable]) -> str:
    output = StringIO()
    writer = csv.writer(output)
    writer.writerow(headers)
    writer.writerows(rows)
    return output.getvalue()


def rows_to_xlsx(headers: list[str], rows: Iterable[Iterable], title: str = "Relatório", language: str = "pt") -> bytes:
    lang = "en" if language == "en" else "pt"
    wb = Workbook()
    ws = wb.active
    ws.title = title[:31]
    ws.append(["Stock Management System" if lang == "en" else "Sistema de Gestão de Stock", "Gestão de Terminais, SA"])
    ws.append([title, f"{'Generated on' if lang == 'en' else 'Gerado em'} {datetime.now().strftime('%Y-%m-%d %H:%M')}"])
    ws.append([])
    ws.append(headers)
    for row in rows:
        ws.append(list(row))
    for cell in ws[4]:
        font = copy(cell.font)
        font.bold = True
        cell.font = font
    for column in ws.columns:
        width = min(max(len(display_value(cell.value)) for cell in column) + 2, 42)
        ws.column_dimensions[column[0].column_letter].width = width
    stream = BytesIO()
    wb.save(stream)
    return stream.getvalue()


def rows_to_docx(
    headers: list[str],
    rows: Iterable[Iterable],
    title: str = "Relatório",
    generated_by: str = "",
    language: str = "pt",
) -> bytes:
    lang = "en" if language == "en" else "pt"
    meta = f"{'Generated on' if lang == 'en' else 'Gerado em'} {datetime.now().strftime('%d/%m/%Y %H:%M')}"
    if generated_by:
        meta += f" | {'Generated by' if lang == 'en' else 'Gerado por'}: {generated_by}"

    def text_run(value: str, bold: bool = False, size: int = 16) -> str:
        bold_xml = "<w:b/>" if bold else ""
        return (
            f"<w:r><w:rPr>{bold_xml}<w:sz w:val=\"{size}\"/></w:rPr>"
            f"<w:t xml:space=\"preserve\">{escape(display_value(value))}</w:t></w:r>"
        )

    def paragraph(value: str, bold: bool = False, size: int = 16, align: str | None = None) -> str:
        jc = f"<w:pPr><w:jc w:val=\"{align}\"/></w:pPr>" if align else ""
        return f"<w:p>{jc}{text_run(value, bold, size)}</w:p>"

    def cell(value: str, bold: bool = False) -> str:
        return f"<w:tc><w:tcPr><w:tcW w:w=\"2200\" w:type=\"dxa\"/></w:tcPr>{paragraph(value, bold, 14)}</w:tc>"

    row_xml = "<w:tr>" + "".join(cell(header, True) for header in headers) + "</w:tr>"
    for row in rows:
        values = list(row)
        row_xml += "<w:tr>" + "".join(cell(values[index] if index < len(values) else "") for index in range(len(headers))) + "</w:tr>"

    document_xml = f"""<?xml version="1.0" encoding="UTF-8" standalone="yes"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body>
    {paragraph("Gestão de Terminais, SA", True, 24, "center")}
    {paragraph(title, True, 30, "center")}
    {paragraph(meta, False, 16, "center")}
    <w:p/>
    <w:tbl>
      <w:tblPr>
        <w:tblW w:w="0" w:type="auto"/>
        <w:tblBorders>
          <w:top w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
          <w:left w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
          <w:bottom w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
          <w:right w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
          <w:insideH w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
          <w:insideV w:val="single" w:sz="4" w:space="0" w:color="D9DDE3"/>
        </w:tblBorders>
      </w:tblPr>
      {row_xml}
    </w:tbl>
    <w:p/>
    {paragraph("Departamento de Tecnologia e Informação - GT, SA", False, 14, "center")}
    <w:sectPr><w:pgSz w:w="16838" w:h="11906" w:orient="landscape"/><w:pgMar w:top="720" w:right="720" w:bottom="720" w:left="720" w:header="360" w:footer="360" w:gutter="0"/></w:sectPr>
  </w:body>
</w:document>"""
    stream = BytesIO()
    with ZipFile(stream, "w", ZIP_DEFLATED) as docx:
        docx.writestr("[Content_Types].xml", """<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types"><Default Extension="rels" ContentType="application/vnd.openxmlformats-package.relationships+xml"/><Default Extension="xml" ContentType="application/xml"/><Override PartName="/word/document.xml" ContentType="application/vnd.openxmlformats-officedocument.wordprocessingml.document.main+xml"/></Types>""")
        docx.writestr("_rels/.rels", """<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"><Relationship Id="rId1" Type="http://schemas.openxmlformats.org/officeDocument/2006/relationships/officeDocument" Target="word/document.xml"/></Relationships>""")
        docx.writestr("word/_rels/document.xml.rels", """<?xml version="1.0" encoding="UTF-8" standalone="yes"?><Relationships xmlns="http://schemas.openxmlformats.org/package/2006/relationships"/>""")
        docx.writestr("word/document.xml", document_xml)
    return stream.getvalue()


def rows_to_pdf(
    headers: list[str],
    rows: Iterable[Iterable],
    title: str = "Relatório",
    generated_by: str = "",
    language: str = "pt",
) -> bytes:
    stream = BytesIO()
    doc = SimpleDocTemplate(
        stream,
        pagesize=landscape(A4),
        rightMargin=1 * cm,
        leftMargin=1 * cm,
        topMargin=1 * cm,
        bottomMargin=1.4 * cm,
    )
    story = [brand_header(title, meta=generated_meta(generated_by, language), width=26 * cm), Spacer(1, 0.35 * cm)]
    styles, _regular, bold = branded_styles()
    cell_style = styles["GTNormalSmall"]
    header_style = cell_style.clone("GTReportHeader")
    header_style.fontName = bold
    header_style.textColor = INK
    rows_list = [[Paragraph(escape(display_value(value)), header_style) for value in headers]]
    rows_list.extend([[Paragraph(escape(display_value(value)), cell_style) for value in row] for row in rows])
    col_count = max(len(headers), 1)
    weights = []
    for header in headers:
        lowered = header.lower()
        if any(term in lowered for term in ("produto", "descr", "item", "observ", "coment", "fornecedor")):
            weights.append(2.2)
        else:
            weights.append(1.0)
    total_weight = sum(weights) or col_count
    story.append(data_table(rows_list, col_widths=[(26 * cm) * weight / total_weight for weight in weights]))
    doc.build(
        story,
        onFirstPage=lambda canvas, d: branded_footer(canvas, d, generated_by, language),
        onLaterPages=lambda canvas, d: branded_footer(canvas, d, generated_by, language),
    )
    return stream.getvalue()
